"""add customer_name to inquiries

Revision ID: 1a3b4cf636ba
Revises: a42cca4a3019
Create Date: 2026-01-15 00:45:02.824998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3b4cf636ba'
down_revision: Union[str, None] = 'a42cca4a3019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('customer_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inquiries', 'customer_name')
    # ### end Alembic commands ###